hugo/layouts/species/list.html
hugo/layouts/species/species_intro.html

Fixes for the following 3 issues: 
1. Species search: cards do not reorder properly when filtered by the search.
2. Species search: no results found warning does not disappear if you re-run the search i.e. delete the search that returned no results. 
3. Lineage ordering in each species introduction page is incorrect. 
**Going to merge if checks pass as still in early stages of project.**

EB-49: Website bug fixes

---

.github/.markdownlint.yaml
hugo/content/add_genome/_index.md
hugo/content/add_genome/recommendations_for_file_formats.md
hugo/content/add_genome/recommendations_for_making_data_public.md
hugo/static/css/styles.css

Added content to the 'add a new genome' info page. Created sub-pages for the recommendations texts since they are long.
Also updated the CSS to improve styling. This is the main reason for the PR, but please also look at the textual content if you want/have time.
- Markdown code notation 
The file format recommendations page use quite a few code examples formatted with back-ticks. The default configuration resulted in colors that deviate from the overall styling of the web page.
Thus updated the CSS with `code {}` and `pre {}` to use `--scilife-light-grey` for backgrounds, and black font. 
Had to use `!important` to override other rules to get it to display. Perhaps this is not best-practice? Please make changes (or revert) as you see fit!
- h3 and h4
In `_index.md` and …

EB-84: Populate "add-species" markdown pages

---

Makefile
data.dockerfile
docker.mk
scripts/dockerbuild.sh
scripts/dockermake.sh
scripts/generate_jbrowse_config.sh
scripts/make_download_targets.sh

This pull request introduces:
- A Dockerfile `data.dockerfile` to build a `swedgene-data` image based on `node` containing the `samtools` and `htslib` dependencies needed to prepare JBrowse data
- A`scripts/dockermake.sh` helper script that spins up a container with the host `data/` directory and `Makefile` mounted
I also reintroduced the ability to limit species to consider. The following example summarizes the new workflow:
```bash
docker build -f data.dockerfile -t swedgene-data .
rm -f data/targets.mk
./scripts/dockermake.sh SPECIES=clupea_harengus build
```
I leave the draft status because it is still a bit rough, but wanted to give you a chance to play with it while I am away next week. 
Cheers :)

Build genomic data in a docker container

---

scripts/dockerbuild.sh
scripts/dockerserve.sh

This PR adds helper scripts to serve the Hugo site locally, with the data directory properly mounted.
- `scripts/dockerbuild.sh site` builds the `hugo-site` image tagged `local`
- `scripts/dockerserve.sh` launches web server on port `8080` with the host `data` directory mounted where JBrowse expects it.
Both scripts can be customized through the use of appropriate `SW_`-prefixed environment variables.

Serve site locally in Docker container

---

.github/workflows/data-builder-container.yml
.github/workflows/hugo-container.yml
README.md
scripts/dockerbuild.sh
scripts/dockermake.sh
scripts/dockerserve.sh
scripts/rename.sh

Prepend `swg-` to our public Docker image names to avoid naming conflicts.
Also included the script used to perform the renaming , if that is something we get into the habit of doing 🙄

Rename Docker images

---

Makefile

This tiny pull request ensures that species directories created by make in `DATA_DIR` are "readable by everyone". In a Kubernetes context, this means that the `nginx` user will be able to read (and hence serve) the JBrowse configuration files.
The proposed modification was necessary because the `--create-dirs` option of `curl`, creates intermediate directories with mode 0750, which makes them unreadable for a user that is not the owner or a member of the group owning the file.

Make species data directories readable to the world

---

docker/data.dockerfile
docker/hugo.dockerfile
docker/hugo.dockerfile.dockerignore
scripts/dockerserve.sh

Hi, 
This is an attempt to reduce the sizes of the docker images. 
I think the first 2 commits for the `hugo.dockerfile` are non controversial, but please feel free to disagree of course.  
For the `data.dockerfile` I have manged to reduce the image size to about 1/4 by using a multi-stage build. I tried to use the Node alpine build at first but ran into a lot of missing libraries/dependencies issues that I gave up on that and instead went for the Node slim build instead. 
```
docker images | grep "swg-data-builder"
swg-data-builder                                local-slim      9a4410320927   20 minutes ago      289MB
ghcr.io/scilifelabdatacentre/swg-data-builder   main            28ea12996ea0   23 hours ago        1.19GB
```
I think the `data.dockerfile` is now a bit more complicated …

EB-103: optimise docker image sizes

---

Makefile
scripts/dockermake.sh

- `make` now only installs (_ie_ copies) new files, or files that have changed since last install
-  `make` picks up `SWG_*` variables from the environment
- `scripts/dockermake.sh` leverages the previous point to dynamically build the flags to pass to `docker run` 
Minor bug fixes include:
- tell `curl` to fails when the HTTP responses have a faulty status code (e.g. 404) instead of putting garbage in `.downloads` creating errors further down the line.
- use `patsubst` rather than `subst` to guarantee prefix-substitutions

Enhanced installation recipe

---

Makefile
scripts/filter.sh
scripts/generate_jbrowse_config.sh
scripts/utils.sh
tests/config/zip_extensions/config.yml
tests/fixtures/tiny_herb/genes.gff
tests/fixtures/zip_extensions/unzipped_genes.gff3

Building on #28, support an extensible set of compression formats for both FASTA and GFF. In particular, no compression at all is allowed. The only limitation is that compression formats be supported by `zcat`.
Highlights:
- The `std_extension` function has been rewritten to ~~use a lot of interesting bash mechanisms~~ be more robust and easily customized
- Files that are not compressed saved with the `.nozip`™ extension
- `bgzip` compression is handled by a single `make` recipe
- `scripts/filter.sh` allows arbitrary pre-gzip transformations to be applied to files

Generalized compression format support

---

Makefile
scripts/make_download_targets
tests/bats/make_download_targets.bats

No longer resort to the`targets.mk` intermediary makefile to define the `DOWNLOAD_TARGETS` variable. Instead, assign the variable afresh from a shell command every time `make` is invoked. 
This ensures that the `DOWNLOAD_TARGETS` always reflect the state of the configuration when make is invoked, also taking into consideration  `SPECIES=rosa_rosae_rosam` restrictions passed on the command line. 
The `targets.mk` was only rebuilt if a configuration file was added or modified. Not if a configuration was removed. And if `targets.mk` was generated when `make` was called without `SPECIES` argument, it would interfere with a subsequent call made with `SPECIES=foo`. So instead of a more elaborate cache invalidation logic, decided to drop the complexity altogether and incur the microscopic …

Avoid caching download targets in targets.mk

---

scripts/dockerserve

The `--dev` flag passed to `scripts/dockerserve` runs `hugo serve` in a docker container, with the working `hugo` directory mounted. It is exposed by default on port `8080`.
This gives a view of the currently checked-out website with the convenience of hot-reloading, without having to install hugo.

Run hugo development server in docker

---

config/clupea_harengus/config.yml
scripts/generate_jbrowse_config

This PR adds support for a `displayName` key in the `assembly` configuration section. 
For illustrative purposes I just set the property for the herring, unsure about what convention to use (latin names or english equivalents) 
The display name appears in the initial assembly selection drop-down in JBrowse. However, the header of the default browser view unfortunately still uses the assembly `name`.
We will likely need to provide default sessions using #34, where the view display name can be configured.

Configure assembly display name

---

hugo/assets/glossary.csv
hugo/content/glossary/_index.md
hugo/layouts/glossary/list.html
hugo/layouts/partials/download_table.html
hugo/layouts/partials/footer.html

Glossary page for the website created, with links to the glossary in the site footer and at the bottom of each species download table. 
Glossary stored at `hugo/assets/glossary.csv` . The file is a .csv file with "|" as delimiter. Commas, quotes etc.. can therefore be used in the file. Note that to style the text (e.g. italicize a word in the definition), markdown syntax can be used. 
I haven't copied over the summary/descriptive text of the glossary page, but this can be added to the file: `hugo/content/glossary/_index.md` when ready (it will sit above the table).

EB-115: Add glossary page

---

.github/workflows/hugo-container.yml
docker/hugo.dockerfile
docker/nginx-custom.conf

This PR is to enable caching images, fonts, js and css files on a user's browser, which is done by editing the nginx config. 
I have tested these changes
**1. locally:** 
```
docker build -t swg-hugo-site:local -f docker/hugo.dockerfile .
docker run -p 8080:8080 swg-hugo-site:local
```
**2. on the [dev cluster](https://swedgene.scilifelab-2-dev.sys.kth.se/)**
using the Hugo docker image created by this branch.
As can be seen from the screenshot the images (and css/fonts etc..) now include a cache policy in their response header so it is behaving as expected. The 2nd load time for a page is now about 1/8 the speed of the initial load time too, so it seems to have had a very nice impact :) 
**Notes:** 
- Regarding cache busting: The `styles.css` file created is …

EB-102: Enable caching images/css/js/fonts on the browser

---

hugo/config.yaml
hugo/layouts/partials/create_description.html
hugo/layouts/partials/head.html

Before this PR only the homepage had a meta tag with a description (found in the <head> of each HTML file). [Lighthouse explains nicely why this is good to have on each page for search engine optimisation](https://developer.chrome.com/docs/lighthouse/seo/meta-description/) 
**The homepage has for example this description:**
`<meta name="description" content="A platform facilitating access and discovery of genome data of non-model eukaryotic species studied in Sweden, hosted by SciLifeLab">`
Now each page is assigned one using the Hugo partial `hugo/layouts/partials/create_description.html`. This includes an automated way to make descriptions for new species so we don't have to worry about that either.

EB-130: Add meta descriptions for each page. 

---

scripts/filter
tests/bats/filter.bats
tests/config/tiny_herb/config.yml

- Ensure BED files are tab-delimited
- As [discussed](https://scilifelab.atlassian.net/browse/EB-131?focusedCommentId=15732) indiscriminately replace every sequence of spaces by a single tab. Let's see how far that gets us.
- Sort BED files while preserving the header lines

Ensure BED files are tab-delimited, sorted, and include headers 

---

.github/workflows/data-builder-container.yml
.github/workflows/hugo-container.yml
.github/workflows/lighthouse.yml
.github/workflows/precommit.yml
.github/workflows/trivy-scan.yml

Hey :) 
We have 5 workflows, 2 of which build images and the other 3 are more testing related. 
For the 3 testing related I have set it up so that both a PR or push to main or prod triggers them to run. 
**For the 2 that build images I have now set it up so that:** 
- On PR no images are built.
- On push to prod, both images are built with tag "prod".
- On push to main both images are built with tag "dev". 
- A workflow_dispatch (manual job) can be triggered to build either image on any branch (but not a fork). The default tag for the workflow dispatch will be "dev", but we have the choice to change that if we want when triggering the workflow. 
I think this matches up with our plan. I've been testing out these settings using a personal repository and there it seems to be working nicely …

EB-179: Configure production and development Docker image builds

---

hugo/layouts/glossary/list.html
hugo/layouts/index.html
hugo/layouts/partials/distrib_map.html
hugo/layouts/partials/download_table.html
hugo/layouts/partials/head.html
hugo/layouts/shortcodes/contact_form.html
hugo/layouts/species/species_assembly.html
hugo/layouts/species/species_download.html

Before this PR, jQuery was added as a dependency for all pages and used in some pages as part of some JS scripts throughout the website. I've now removed it to only be used when the Datatables library is loaded (jquery is a dependency) and replaced the other instances with vanilla JS. This therefore helps to improve the sites' load speed by not having to load jquery from a CDN.  
I've also taken the opportunity to move all downloads of scripts/style sheets to one place, ` head.html`, so it is easier to keep track of. Finally I've added [some preconnects](https://developer.chrome.com/docs/lighthouse/performance/uses-rel-preconnect) too to help with the site's loading speeds.

EB-141: Use vanilla JS instead of jquery where possible

---

hugo/content/about/_index.md
hugo/content/about/sv/index.md
hugo/content/contribute/_index.md
hugo/content/terms/_index.md
hugo/layouts/partials/footer.html

This PR contains a few minor commits related to the commits in #64, a PR that was already merged in order to simplify the current branch flow.   
First of all, thanks for your great work on the pages @apfuentes. Well done! 
I took the liberty to commit the minor typos that I spotted in the branch. I hope that the commit descriptions should be self-explanatory. For 418a57b4b2f6a743158e7bc826f5b3e43c5e37ba, I assume that the Terms page should go in the footer, but please feel free to revert that commit if that was a premature decision from my side. 
I have not reviewed the FAQ and User Guide parts, since that will come in its own PR. But the little I saw so far looks good!
Here are some other comments / discussion points:
- Recommendations page
the new title affects the breadcrumbs on the …

Content tweaks for first release

---

CITATION.cff
config/linum_trigynum/config.yml
hugo/assets/linum_trigynum/data_tracks.json
playwright/tests/test_species_download_page.py

For the next release, it would be good to have a fix in place for the in inaccessible _L. trigynum_ link: b9caa0a. If the broken link gets fixed in the foreseeable future, supporting it it would mainly be a matter of reverting the edits in b9caa0a. But if the solution is to ask the submitter to upload the file anew, there will likely be a new url that needs to be added.
The other two commits are side things that I though would be of interest to have for the next release.
The first commit regards modifying the playwright test back to a previous state where it catches and warns for the broken link. I thought this was a fun exercise in applying the playwright tests in the troubleshooting work-flow. Command:
```
pytest playwright/tests/test_species_download_page.py::test_table_links …
```

Temporary fix for handling inaccessible data track url 

---

CONTRIBUTING.adoc

This PR drafts a Github contribution guide for users who would be willing to submit new species through pull requests.
I could be paired with an adequate pull request template. 
I plan to add subsequent sections for undaunted users who would like to get started with their species content
using `hugo new` or `add_new_species.py`.
Finally, I used the [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/) format that was praised at PyCon to give it a try. If you prefer sticking to Markdown, it will give me a nice opportunity to try Pandoc 🙂 
All remarks welcome of course, this is an experiment!

EB-390: Github contrbution guide
